version: "3.7"
services:
  db:
    # container_name: blinkable-mysql
    image: mysql
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: blinkable
      MYSQL_DATABASE: blinkable
      MYSQL_USER: blinkable
      MYSQL_PASSWORD: blinkable
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - 3306:3306
    networks:
      - blink

  redis:
    image: redis
    # restart: always
    ports:
      - 6379:6379
    networks:
      - blink
    command: redis-server --requirepass blinkable

  oss:
    image: minio/minio
    hostname: "minio"
    ports:
      - 9000:9000 # api 端口
      - 9001:9001 # 控制台端口
    environment:
      MINIO_ACCESS_KEY: blinkableKey
      MINIO_SECRET_KEY: blinkableKey
      MINIO_ROOT_USER: blinkable
      MINIO_ROOT_PASSWORD: blinkable
    # volumes:
      # - ./minio/data:/data
    command: server --console-address ':9001' /data
    privileged: true
    # restart: always
    networks:
      - blink

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./deployment/otel.yml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888" # pprof extension
      - "8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "55679" # zpages extension
    depends_on:
      - jaeger-all-in-one
    networks:
        - blink

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      # - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
    ports:
      - "16686:16686"
      - "14268"
      - "14250:14250"
      - "6831:6831"
      - "4317"   # OTLP gRPC receiver
    networks:
      - blink
  # Victoriametrics
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics
    ports:
      - "8428:8428"
      - "8089:8089"
      - "8089:8089/udp"
      - "2003:2003"
      - "2003:2003/udp"
      - "4242:4242"
    command:
      - "--storageDataPath=/storage"
      - "--graphiteListenAddr=:2003"
      - "--opentsdbListenAddr=:4242"
      - "--httpListenAddr=:8428"
      - "--influxListenAddr=:8089"
    #restart: always
    networks:
        - blink

  # Grafana
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    networks:
        - blink

networks:
  blink:
    external: true
