version: "3.7"
services:
  db:
    image: mysql
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: blinkable
      MYSQL_DATABASE: blinkable
      MYSQL_USER: blinkable
      MYSQL_PASSWORD: blinkable
    ports:
      - 3306:3306

  adminer:
    image: adminer
    # restart: always
    ports:
      - 18080:8080

  redis:
    image: redis
    # restart: always
    ports:
      - 16379:6379

  oss:
    image: minio/minio
    hostname: "minio"
    ports:
      - 9000:9000 # api 端口
      - 9001:9001 # 控制台端口
    environment:
      MINIO_ACCESS_KEY: blinkableKey
      MINIO_SECRET_KEY: blinkableKey
      MINIO_ROOT_USER: blinkable
      MINIO_ROOT_PASSWORD: blinkable
    volumes:
      - ./minio/data:/data
    command: server --console-address ':9001' /data
    privileged: true
    # restart: always

  etcd:
    image: bitnami/etcd
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
