// Code generated by Kitex v0.7.3. DO NOT EDIT.
package homepageservice

import (
	homepage "blinkable/server/kitex_gen/Homepage"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler homepage.HomepageService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
