version: "3.7"
services:
  nacos:
    image: nacos/nacos-server:v2.3.0
    container_name: blinkable-nacos-server
    env_file:
      - ../env/nacos-standlone-mysql.env
    # volumes:
    #   - ./standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      mysql:
        condition: service_healthy
    #restart: always
    networks:
      - nacos
  mysql:
    container_name: blinkable-nacos-db
    build:
      context: .
      dockerfile: ./image/mysql/8/Dockerfile
    image: nacos-docker/nacos-mysql:8.0.30
    env_file:
      - ../env/mysql.env
    # volumes:
    #   - ./mysql:/var/lib/mysql
    ports:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - nacos
networks:
  nacos:
    external: true
